### PR TITLE
Added german translations

### PR DESCRIPTION
**Pull request by Tyratox**
I translated the strings to german.

### CODE REVIEW

**Comment by ronalfy** [comment]
Thank you.  We'll get this in the .org version as soon as we can.

**Comment by ronalfy** [comment]
Would you like some type of credit in the readme.txt file?  If so, let me know.

**Comment by Tyratox** [comment]
:+1: 
Nah, it's alright, thanks

**Comment by ronalfy** [comment]
I sent you an email, but do you have a wordpress.org profile? I'd like to add you as a translator on translate.wordpress.org.

**Pull request merged**
